baseURL = "https://hugo-base-theme.netlify.com/"
languageCode = "en-us"
title = "Hugo Base"
theme = "brionz-base"
sectionPagesMenu = "main"
googleAnalytics = "UA-123-452-1"
summaryLength = "25"

[params]
  title = "Front Page"
  description = "This is homepage of bRionZ Base Hugo boilerplate theme."
  image = ["site-feature-image.jpg"]

